// <auto-generated />
namespace ProjectAbi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class step2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(step2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005161644360_step2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
